services:

  dagster-code-location:
    build:
      context: .
    container_name: dagster_code_location
    restart: always
    working_dir: /app

    environment:
      DAGSTER_HOME: /app/dagster_home
      PYTHONPATH: /app/src

    volumes:
      - .:/app
      

    command:
      - sh
      - -c
      - |
        sleep 15 &&
        dagster api grpc \
        -h 0.0.0.0 \
        -p 4000 \
        -m dagster_aws_demo.definitions

    ports:
      - "4000:4000"

    healthcheck:
      test:
        [
          "CMD",
          "python",
          "-c",
          "import socket; s=socket.socket(); s.connect(('localhost',4000)); s.close()"
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s


  dagster-webserver:
    build:
      context: .
    container_name: dagster_webserver
    restart: always
    working_dir: /app

    environment:
      DAGSTER_HOME: /app/dagster_home
      PYTHONPATH: /app/src

    volumes:
      - .:/app
  

    depends_on:
      dagster-code-location:
        condition: service_healthy

    command:
      - dagster-webserver
      - -w
      - /app/workspace.yml
      - -h
      - "0.0.0.0"
      - -p
      - "3000"

    ports:
      - "3000:3000"

    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "-f",
          "http://localhost:3000/server_info"
        ]
      interval: 15s
      timeout: 5s
      retries: 5
      start_period: 20s


  dagster-daemon:
    build:
      context: .
    container_name: dagster_daemon
    restart: always
    working_dir: /app

    environment:
      DAGSTER_HOME: /app/dagster_home
      PYTHONPATH: /app/src

    volumes:
      - .:/app
     
    depends_on:
      dagster-code-location:
        condition: service_healthy

    command:
      - dagster-daemon
      - run
      - -w
      - /app/workspace.yml

    healthcheck:
      test:
        [
          "CMD",
          "pgrep",
          "-f",
          "dagster-daemon"
        ]
      interval: 15s
      timeout: 5s
      retries: 5
      start_period: 20s